# Generated by Django 3.0.4 on 2020-03-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ApprovalStatus',
            field=models.CharField(choices=[('APP', 'APPROVED'), ('RE', 'REJECTED'), ('SUB', 'SUBMITTED')], default='SUB', max_length=5),
        ),
    ]
