# Generated by Django 3.0.4 on 2020-03-28 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0003_auto_20200327_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='TimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 22, 9, 20, 66970, tzinfo=utc), verbose_name='TimeStamp'),
            preserve_default=False,
        ),
    ]
