# Generated by Django 3.0.4 on 2020-04-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0004_comments_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('EventsMiddleLayerAdmin', 'can see his respective group(s) details (acts as group admin)'), ('EventsSuperAdmin', 'Can see all groups details without being part of them')],
            },
        ),
    ]
